services:
  media_db:
    image: postgres:latest
    container_name: media_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=mediadb
    networks:
      - media_network
    volumes:
      - media_volume:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus-server
    ports:
      - "9090:9090"
    expose:
      - 9090
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    networks:
      - media_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana-oss
    container_name: grafana-server
    environment:
      - GF_SERVER_HTTP_PORT=9001
    ports:
      - "9001:9001"
    expose:
      - 9001
    volumes:
      - grafana_volume:/var/lib/grafana
    networks:
      - media_network

networks:
  media_network:
    driver: bridge

volumes:
  media_volume:
  grafana_volume: {}
