services:
  media_db:
    image: postgres:latest
    container_name: media_db
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=mediadb
    networks:
      - media_network
    volumes:
      - media_volume:/var/lib/postgresql/data

networks:
  media_network:
    driver: bridge

volumes:
  media_volume:
