global:
  scrape_interval: "5s"

scrape_configs:
  - job_name: "media-api"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["host.docker.internal:3000"]

  - job_name: "prometheus"
    metrics_path: "/metrics"
    scheme: "http"
    static_configs:
      - targets: ["localhost:9090"]
